---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: sso
  labels:
    app: sso
spec:
  externalAccess:
    enabled: true
  additionalOptions:
    - name: https-client-auth
      value: request
  instances: 1
